% foldername = '/projectnb/cruzmartinlab/lab_data/WWY_080116_3/cell-bodies-2Hz/Results/';
LAGMAX = 60;
paninskidff = false;
roifile = [];

%% Load preprocessed images
    [trigs,dFF,N,spatmap,corrIm] = ...
        processCaImStack(foldername,roifile,paninskidff,...
        'maxNeurons',1000,...
        'estNeuronSize',10,... % 4 is good for axons; 8 for cell bodies (for WWY_080116_3 data)
        'smallrun',false,...
        'dilation',1,...
        'conn_comp',false,... % set to false for axons
        'refine',false,... 
        'require_overlap',true,... % set to false for axons
        'init_method','greedy',... % 'greedy' for somas, 'sparse_NMF' for axons
        'ARp',2);
